# Generated by Django 4.1.13 on 2024-01-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='posts',
            field=models.ManyToManyField(related_name='authors', to='backend.post'),
        ),
    ]
