# Generated by Django 4.1.13 on 2024-01-30 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_image_remove_post_images_alter_post_id_postimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='posts', through='backend.PostImage', to='backend.image'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images_through', to='backend.image'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images_through', to='backend.post'),
        ),
    ]
